import type { PreviewCommand, PreviewConfig, PreviewPin } from "../shared/preview";
import type { WebsiteAnchor } from "../shared/types";
import { previewLocale, previewMessage, previewPinLabel, type PreviewMessageKey } from "./messages";
import { ADD_COMMENT_CURSOR, COMMENT_CURSOR } from "./cursor";
import { captureViewport } from "./capture";
import { newCaptureId } from "../shared/capture-canvas";

// This file is independently authored. It runs inside the isolated preview document,
// never in the Repère application origin. No session cookie or API token enters here.
const node = document.getElementById("repere-preview-config");
if (node && window.parent !== window) {
  const config = JSON.parse(node.textContent || "{}") as PreviewConfig;
  if (
    typeof config.appOrigin === "string" &&
    typeof config.targetOrigin === "string" &&
    typeof config.channel === "string"
  ) {
    initialize(config);
  }
}

function initialize(config: PreviewConfig) {
  const proxyOrigin = location.origin;
  const localeKey = `repere-locale:${config.channel}`;
  let locale = previewLocale(config.locale);
  try {
    locale = previewLocale(sessionStorage.getItem(localeKey), locale);
  } catch {
    /* Storage may be disabled by the browser. */
  }
  function localizeServicePage() {
    // Only pages generated by Repère opt in. Never translate the website's own content.
    if (config.servicePage !== "redirect") return;
    for (const element of document.querySelectorAll<HTMLElement>("[data-repere-message]")) {
      const key = element.dataset.repereMessage;
      if (["redirectTitle", "redirectHeading", "redirectLink", "redirectHint"].includes(key ?? ""))
        element.textContent = previewMessage(locale, key as PreviewMessageKey);
    }
    document.documentElement.lang = locale;
  }
  const originalUrl = () =>
    `${config.targetOrigin}${location.pathname}${location.search}${location.hash}`;
  function toProxy(value: string): string {
    // Relative paths and fragments must retain document.baseURI semantics.
    if (!/^(?:https?:)?\/\//i.test(value.trim())) return value;
    try {
      const url = new URL(value, originalUrl());
      if (url.origin === config.targetOrigin)
        return `${proxyOrigin}${url.pathname}${url.search}${url.hash}`;
    } catch {
      /* The native API will handle invalid URLs. */
    }
    return value;
  }
  const reportLocation = (type: "ready" | "location" = "location") => {
    parent.postMessage(
      {
        source: "repere-preview",
        channel: config.channel,
        type,
        url: originalUrl(),
        title: document.title,
      },
      config.appOrigin,
    );
  };

  // Keep ordinary relative requests untouched. Only same-target absolute URLs need
  // translation because their browser origin is now the isolated preview host.
  const nativeFetch = window.fetch.bind(window);
  window.fetch = (input, init) => {
    if (input instanceof Request) {
      const url = toProxy(input.url);
      return nativeFetch(url === input.url ? input : new Request(url, input), init);
    }
    return nativeFetch(toProxy(String(input)), init);
  };
  // WebSockets use the same isolated host; unrelated socket origins stay native.
  const NativeWebSocket = window.WebSocket;
  window.WebSocket = new Proxy(NativeWebSocket, {
    construct(target, args: ConstructorParameters<typeof WebSocket>) {
      const url = new URL(String(args[0]), location.href);
      const httpOrigin = url.origin.replace(/^ws/, "http");
      if (httpOrigin === config.targetOrigin) {
        const preview = new URL(proxyOrigin);
        url.protocol = preview.protocol === "https:" ? "wss:" : "ws:";
        url.host = preview.host;
        args[0] = url;
      }
      return Reflect.construct(target, args);
    },
  });
  const nativeOpen = XMLHttpRequest.prototype.open;
  Object.defineProperty(XMLHttpRequest.prototype, "open", {
    configurable: true,
    writable: true,
    value: function (this: XMLHttpRequest, ...args: unknown[]) {
      if (typeof args[1] === "string" || args[1] instanceof URL) args[1] = toProxy(String(args[1]));
      return Reflect.apply(nativeOpen, this, args);
    },
  });
  for (const key of ["pushState", "replaceState"] as const) {
    const native = history[key].bind(history);
    history[key] = (data, unused, url) => {
      native(data, unused, url == null ? url : toProxy(String(url)));
      reportLocation();
      schedule();
    };
  }
  const nativeWindowOpen = window.open.bind(window);
  window.open = (url, target, features) =>
    nativeWindowOpen(
      url == null ? url : toProxy(String(url)),
      target,
      `${features || ""},noopener`,
    );

  const cookieDescriptor = Object.getOwnPropertyDescriptor(Document.prototype, "cookie");
  if (cookieDescriptor?.get && cookieDescriptor.set && cookieDescriptor.configurable) {
    Object.defineProperty(Document.prototype, "cookie", {
      configurable: true,
      get: cookieDescriptor.get,
      set(value: string) {
        // Cookie namespaces remain in the browser, isolated by preview hostname.
        // No server-side cookie jar can be replayed with a leaked preview URL.
        const clean = String(value)
          .replace(/;\s*domain=[^;]*/gi, "")
          .replace(/;\s*samesite=[^;]*/gi, "");
        cookieDescriptor.set!.call(this, `${clean}; SameSite=None; Secure; Partitioned`);
      },
    });
  }

  const URL_ATTRIBUTES = new Set([
    "href",
    "src",
    "action",
    "formaction",
    "poster",
    "data",
    "xlink:href",
  ]);
  function mapAttribute(name: string, value: string) {
    if (URL_ATTRIBUTES.has(name)) return toProxy(value);
    if (name === "srcset")
      return value.replace(
        /(^|,\s*)([^\s,]+)(?=\s|,|$)/g,
        (_, prefix: string, url: string) => prefix + toProxy(url),
      );
    if (name === "style") return value.split(config.targetOrigin).join(proxyOrigin);
    return value;
  }
  const nativeSetAttribute = Element.prototype.setAttribute;
  Element.prototype.setAttribute = function (name, value) {
    nativeSetAttribute.call(this, name, mapAttribute(name.toLowerCase(), String(value)));
  };
  // Property setters otherwise start loading resources before a MutationObserver runs.
  for (const [prototype, property] of [
    [HTMLAnchorElement.prototype, "href"],
    [HTMLLinkElement.prototype, "href"],
    [HTMLImageElement.prototype, "src"],
    [HTMLImageElement.prototype, "srcset"],
    [HTMLScriptElement.prototype, "src"],
    [HTMLIFrameElement.prototype, "src"],
    [HTMLFormElement.prototype, "action"],
    [HTMLSourceElement.prototype, "src"],
    [HTMLSourceElement.prototype, "srcset"],
    [HTMLMediaElement.prototype, "src"],
  ] as const) {
    const descriptor = Object.getOwnPropertyDescriptor(prototype, property);
    if (!descriptor?.set || !descriptor.configurable) continue;
    Object.defineProperty(prototype, property, {
      ...descriptor,
      set(value: string) {
        descriptor.set!.call(this, mapAttribute(property, String(value)));
      },
    });
  }

  let mode: "browse" | "comment" = "browse";
  let pins: PreviewPin[] = [];
  let selected: string | null = null;
  let host: HTMLElement | null = null;
  let root: ShadowRoot | null = null;
  let draft: WebsiteAnchor | null = null;
  let scheduled = false;
  let lastUrl = originalUrl();
  let hovered: Element | null = null;
  let activeCapture: AbortController | null = null;
  const pinElements = new Map<string, HTMLButtonElement>();
  const focusKey = `repere-focus:${config.channel}`;
  const cursorStyle = document.createElement("style");
  cursorStyle.dataset.repereCursor = "";

  function updateCursor() {
    if (mode !== "comment") {
      cursorStyle.remove();
      return;
    }
    // Override page-specific link/text cursors only while placing feedback. Removing
    // our stylesheet restores the website's own styles without modifying its nodes.
    const value = draft ? COMMENT_CURSOR : ADD_COMMENT_CURSOR;
    const css = `:root,:root *,:root *::before,:root *::after{cursor:${value}!important}`;
    if (cursorStyle.textContent !== css) cursorStyle.textContent = css;
    if (!cursorStyle.isConnected) document.documentElement.append(cursorStyle);
  }

  function overlay() {
    if (host?.isConnected && root) return root;
    if (!document.body) return null;
    host = document.createElement("repere-annotations");
    host.style.cssText =
      "all:initial;position:fixed;inset:0;z-index:2147483647;pointer-events:none;contain:layout style;display:block;";
    root = host.attachShadow({ mode: "open" });
    const style = document.createElement("style");
    style.textContent = `:host{all:initial}button{all:initial;box-sizing:border-box;position:absolute;width:29px;height:33px;border:2px solid #fff;border-radius:16px 16px 16px 2px;background:#3657e8;color:#fff;font:700 11px system-ui;display:grid;place-items:center;pointer-events:auto;cursor:pointer;box-shadow:0 2px 10px #3657e840;transform:translate(-4px,-28px)}button.selected{background:#2846c9;color:#fff;box-shadow:0 0 0 4px #3657e830}button.resolved{background:#8995b8}button:focus-visible{outline:3px solid #7590ff;outline-offset:3px}.outline{position:absolute;border:1px solid #3657e8;background:#3657e808;border-radius:2px;pointer-events:none;box-sizing:border-box}.draft{background:#3657e8;color:#fff;pointer-events:none}`;
    style.textContent += `button{cursor:${COMMENT_CURSOR}}`;
    root.append(style);
    document.body.append(host);
    pinElements.clear();
    return root;
  }

  function findElement(anchor: WebsiteAnchor) {
    let element: Element | null = null;
    try {
      element = anchor.selector ? document.querySelector(anchor.selector) : null;
    } catch {
      /* Stale selector. */
    }
    const text = element?.textContent?.trim().replace(/\s+/g, " ") || "";
    if (anchor.text && element && !text.startsWith(anchor.text)) return null;
    return element;
  }
  function position(anchor: WebsiteAnchor) {
    const element = findElement(anchor);
    const rect = element?.getBoundingClientRect();
    return {
      x: rect ? rect.left + rect.width * anchor.x : anchor.documentX - scrollX,
      y: rect ? rect.top + rect.height * anchor.y : anchor.documentY - scrollY,
      matched: !!rect,
    };
  }
  function paint() {
    scheduled = false;
    updateCursor();
    if (!pins.length && !draft && mode !== "comment") {
      host?.remove();
      host = null;
      root = null;
      pinElements.clear();
      return;
    }
    const shadow = overlay();
    if (!shadow) return;
    const visibleIds = new Set<string>();
    for (const pin of pins) {
      if (pin.anchor.url !== originalUrl()) continue;
      const point = position(pin.anchor);
      if (point.x < 0 || point.y < 0 || point.x > innerWidth || point.y > innerHeight) continue;
      visibleIds.add(pin.id);
      let element = pinElements.get(pin.id);
      if (!element) {
        element = document.createElement("button");
        element.type = "button";
        element.textContent = String(pin.number);
        element.addEventListener("click", (event) => {
          event.preventDefault();
          event.stopPropagation();
          parent.postMessage(
            { source: "repere-preview", channel: config.channel, type: "select", id: pin.id },
            config.appOrigin,
          );
        });
        shadow.append(element);
        pinElements.set(pin.id, element);
      }
      element.className = `${selected === pin.id ? "selected" : ""} ${pin.status === "resolved" ? "resolved" : ""}`;
      element.style.left = `${point.x}px`;
      element.style.top = `${point.y}px`;
      element.setAttribute("aria-label", previewPinLabel(locale, pin.number));
      element.title = previewPinLabel(locale, pin.number, !point.matched);
    }
    for (const [id, element] of pinElements)
      if (!visibleIds.has(id)) {
        element.remove();
        pinElements.delete(id);
      }
    shadow.querySelector(".draft")?.remove();
    if (draft && draft.url === originalUrl()) {
      const point = position(draft);
      const element = document.createElement("button");
      element.type = "button";
      element.tabIndex = -1;
      element.setAttribute("aria-hidden", "true");
      element.className = "draft";
      element.style.left = `${point.x}px`;
      element.style.top = `${point.y}px`;
      shadow.append(element);
    }
    shadow.querySelector(".outline")?.remove();
    if (mode === "comment" && hovered?.isConnected) {
      const rect = hovered.getBoundingClientRect();
      const outline = document.createElement("div");
      outline.className = "outline";
      outline.style.cssText = `left:${rect.left}px;top:${rect.top}px;width:${rect.width}px;height:${rect.height}px;`;
      shadow.prepend(outline);
    }
  }
  function schedule() {
    if (!scheduled) {
      scheduled = true;
      requestAnimationFrame(paint);
    }
  }

  function capture(element: Element, x: number, y: number): WebsiteAnchor {
    const rect = element.getBoundingClientRect();
    const parts: string[] = [];
    let cursor: Element | null = element;
    while (cursor && parts.length < 20) {
      if (cursor.id) {
        const id = `#${CSS.escape(cursor.id)}`;
        if (document.querySelectorAll(id).length === 1) {
          parts.unshift(id);
          break;
        }
      }
      const parentElement: Element | null = cursor.parentElement;
      const siblings: Element[] = parentElement
        ? Array.from(parentElement.children).filter((item) => item.tagName === cursor!.tagName)
        : [cursor];
      parts.unshift(`${cursor.tagName.toLowerCase()}:nth-of-type(${siblings.indexOf(cursor) + 1})`);
      cursor = parentElement;
    }
    return {
      type: "website",
      url: originalUrl(),
      selector: parts.join(" > "),
      text: element.textContent?.trim().replace(/\s+/g, " ").slice(0, 300) || null,
      x: rect.width ? Math.max(0, Math.min(1, (x - rect.left) / rect.width)) : 0,
      y: rect.height ? Math.max(0, Math.min(1, (y - rect.top) / rect.height)) : 0,
      documentX: Math.max(0, x + scrollX),
      documentY: Math.max(0, y + scrollY),
      viewportWidth: innerWidth,
      viewportHeight: innerHeight,
    };
  }
  function focusAnchor(anchor: WebsiteAnchor) {
    if (new URL(anchor.url).origin !== config.targetOrigin) return;
    if (anchor.url !== originalUrl()) {
      sessionStorage.setItem(focusKey, JSON.stringify(anchor));
      location.assign(toProxy(anchor.url));
      return;
    }
    const element = findElement(anchor);
    if (element) element.scrollIntoView({ block: "center", inline: "center", behavior: "smooth" });
    else
      scrollTo({
        left: Math.max(0, anchor.documentX - innerWidth / 2),
        top: Math.max(0, anchor.documentY - innerHeight / 2),
        behavior: "smooth",
      });
    schedule();
  }

  window.addEventListener("message", (event: MessageEvent<PreviewCommand>) => {
    if (
      event.source !== parent ||
      event.origin !== config.appOrigin ||
      event.data?.source !== "repere" ||
      event.data.channel !== config.channel
    )
      return;
    const message = event.data;
    switch (message.type) {
      case "init":
        localizeServicePage();
        reportLocation("ready");
        break;
      case "locale":
        locale = previewLocale(message.locale, locale);
        try {
          sessionStorage.setItem(localeKey, locale);
        } catch {
          /* Browser storage is optional. */
        }
        localizeServicePage();
        schedule();
        break;
      case "mode":
        if (message.mode === "browse" || message.mode === "comment") {
          mode = message.mode;
          if (mode === "browse") {
            draft = null;
            hovered = null;
          }
          schedule();
        }
        break;
      case "pins":
        if (Array.isArray(message.pins)) {
          pins = message.pins.slice(0, 500);
          selected = message.selected;
          if (selected) draft = null;
          schedule();
        }
        break;
      case "focus":
        if (message.anchor?.type === "website") focusAnchor(message.anchor);
        break;
      case "draft":
        draft = message.anchor;
        schedule();
        break;
      case "navigate":
        try {
          const target = new URL(message.url);
          if (target.origin === config.targetOrigin) location.assign(toProxy(target.href));
        } catch {
          /* Invalid address remains in parent. */
        }
        break;
      case "back":
        history.back();
        break;
      case "forward":
        history.forward();
        break;
      case "reload":
        location.reload();
        break;
    }
  });
  window.addEventListener(
    "pointermove",
    (event) => {
      if (mode !== "comment" || (host && event.composedPath().includes(host))) return;
      hovered = event.target instanceof Element ? event.target : null;
      schedule();
    },
    { passive: true },
  );
  window.addEventListener(
    "pointerdown",
    (event) => {
      if (mode === "comment" && !(host && event.composedPath().includes(host))) {
        event.preventDefault();
        event.stopImmediatePropagation();
      }
    },
    true,
  );
  window.addEventListener(
    "click",
    (event) => {
      if (host && event.composedPath().includes(host)) return;
      const element = event.target instanceof Element ? event.target : null;
      if (!element) return;
      if (mode === "comment") {
        event.preventDefault();
        event.stopImmediatePropagation();
        const capturedAt = new Date().toISOString();
        const captureId = newCaptureId();
        draft = capture(element, event.clientX, event.clientY);
        activeCapture?.abort();
        const controller = new AbortController();
        activeCapture = controller;
        // Start the synchronous snapshot before the parent opens its composer and
        // potentially resizes this viewport. Delivery is asynchronous and ID-bound.
        const pendingCapture = captureViewport(
          { x: event.clientX, y: event.clientY, capturedAt },
          controller.signal,
        );
        parent.postMessage(
          {
            source: "repere-preview",
            channel: config.channel,
            type: "anchor",
            anchor: draft,
            captureId,
          },
          config.appOrigin,
        );
        void pendingCapture.then((capture) => {
          if (activeCapture === controller) activeCapture = null;
          parent.postMessage(
            {
              source: "repere-preview",
              channel: config.channel,
              type: "capture",
              captureId,
              capture,
            },
            config.appOrigin,
          );
        });
        schedule();
        return;
      }
      const link = element.closest("a[href]");
      if (link) {
        const href = link.getAttribute("href") || "";
        const next = toProxy(href);
        if (next !== href) nativeSetAttribute.call(link, "href", next);
        try {
          const destination = new URL(next, document.baseURI);
          if (
            ["http:", "https:"].includes(destination.protocol) &&
            destination.origin !== proxyOrigin
          ) {
            nativeSetAttribute.call(link, "target", "_blank");
            nativeSetAttribute.call(link, "rel", "noopener noreferrer");
          }
        } catch {
          /* Let the native link handle non-URL protocols. */
        }
      }
    },
    true,
  );
  window.addEventListener(
    "keydown",
    (event) => {
      if (event.key === "Escape" && mode === "comment") {
        draft = null;
        hovered = null;
        schedule();
      }
    },
    true,
  );
  window.addEventListener("scroll", schedule, { capture: true, passive: true });
  window.addEventListener("resize", schedule, { passive: true });
  window.addEventListener("pagehide", () => activeCapture?.abort());
  window.addEventListener("popstate", () => {
    reportLocation();
    schedule();
  });
  window.addEventListener("hashchange", () => {
    reportLocation();
    schedule();
  });

  function rewrite(element: Element) {
    if (element === host || element.id === "repere-preview-config") return;
    for (const attribute of Array.from(element.attributes)) {
      const value = mapAttribute(attribute.name, attribute.value);
      if (value !== attribute.value) nativeSetAttribute.call(element, attribute.name, value);
    }
    if (element.tagName === "STYLE" && element.textContent?.includes(config.targetOrigin))
      element.textContent = element.textContent.split(config.targetOrigin).join(proxyOrigin);
  }
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.target === host || (host && host.contains(mutation.target))) continue;
      if (mutation.type === "attributes" && mutation.target instanceof Element)
        rewrite(mutation.target);
      for (const added of mutation.addedNodes)
        if (added instanceof Element && added !== host) {
          rewrite(added);
          added.querySelectorAll("[href],[src],[srcset],[action],[style],style").forEach(rewrite);
        }
    }
    schedule();
  });
  observer.observe(document.documentElement, {
    childList: true,
    subtree: true,
    attributes: true,
    attributeFilter: [...URL_ATTRIBUTES, "srcset", "style"],
  });
  function ready() {
    document.querySelectorAll("[href],[src],[srcset],[action],[style],style").forEach(rewrite);
    reportLocation("ready");
    const pending = sessionStorage.getItem(focusKey);
    if (pending) {
      sessionStorage.removeItem(focusKey);
      try {
        const anchor = JSON.parse(pending) as WebsiteAnchor;
        setTimeout(() => focusAnchor(anchor), 300);
      } catch {
        /* Previous page state may be stale. */
      }
    }
    if (document.body) new ResizeObserver(schedule).observe(document.body);
  }
  if (document.readyState === "loading")
    document.addEventListener("DOMContentLoaded", ready, { once: true });
  else ready();
  // CSS animations and late hydration can move anchors without changing a DOM attribute.
  setInterval(() => {
    if (originalUrl() !== lastUrl) {
      lastUrl = originalUrl();
      draft = null;
      reportLocation();
    }
    if (pins.length || draft) schedule();
  }, 250);
}
