#!/usr/bin/env node
import { randomBytes } from "node:crypto";
import { access, appendFile, chmod, readFile, writeFile } from "node:fs/promises";
import { createServer } from "node:net";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(root, ".env");
const envOnly = process.argv.includes("--env-only");
const compose = ["compose", "-f", "compose.yaml", "-f", "compose.dev.yaml"];
const secret = () => randomBytes(32).toString("hex");
const portAvailable = (port) =>
  new Promise((resolve) => {
    const server = createServer();
    server.once("error", () => resolve(false));
    server.listen(port, "127.0.0.1", () => server.close(() => resolve(true)));
  });
async function availablePort(start, reserved = []) {
  for (let port = start; port < start + 100; port++) {
    if (!reserved.includes(port) && (await portAvailable(port))) return port;
  }
  throw new Error(`No free local port found near ${start}.`);
}
function run(command, args) {
  const result = spawnSync(command, args, { cwd: root, stdio: "inherit" });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}
try {
  let exists = true;
  try {
    await access(envPath);
  } catch {
    exists = false;
  }
  if (!exists) {
    const appPort = await availablePort(3000);
    const previewPort = await availablePort(3001, [appPort]);
    const mysqlPort = await availablePort(3308);
    const mailpitPort = await availablePort(8026);
    const smtpPort = await availablePort(1026);
    const mysqlPassword = secret();
    const content = `# Generated by Repère setup. This file contains secrets. Do not commit.\nAPP_PORT=${appPort}\nAPP_URL=http://localhost:${appPort}\nPREVIEW_PORT=${previewPort}\nPREVIEW_BASE_URL=http://localhost:${previewPort}\nPROXY_INTERNAL_URL=http://127.0.0.1:${previewPort}\nPROXY_SECRET=${secret()}\nMYSQL_PORT=${mysqlPort}\nMYSQL_PASSWORD=${mysqlPassword}\nMYSQL_ROOT_PASSWORD=${secret()}\nDATABASE_URL=mysql://repere:${mysqlPassword}@127.0.0.1:${mysqlPort}/repere\nSESSION_SECRET=${secret()}\nUPLOAD_DIR=./uploads\nSMTP_HOST=127.0.0.1\nSMTP_PORT=${smtpPort}\nSMTP_USER=\nSMTP_PASSWORD=\nSMTP_FROM=Repere <hello@repere.local>\nSMTP_SECURE=false\nMAILPIT_PORT=${mailpitPort}\nMAILPIT_SMTP_PORT=${smtpPort}\nMAILPIT_URL=http://127.0.0.1:${mailpitPort}\nALLOWED_EMAIL_DOMAINS=\nPREVIEW_MAX_SESSIONS=100\nPREVIEW_SESSION_TTL_MS=3600000\nPREVIEW_MAX_HTML_BYTES=8388608\nPREVIEW_ALLOWED_PRIVATE_HOSTS=localhost,127.0.0.1\nE2E_WEBSITE_URL=http://app:3000/demo-site\n`;
    await writeFile(envPath, content, { mode: 0o600, flag: "wx" });
    console.log("Created .env with unique secrets and available local ports.");
    console.log(`Application: http://localhost:${appPort}`);
    console.log(`Local email inbox: http://localhost:${mailpitPort}`);
  } else {
    const content = await readFile(envPath, "utf8");
    const settings = new Map(
      [...content.matchAll(/^[ \t]*(?:export[ \t]+)?([A-Z_][A-Z0-9_]*)[ \t]*=[ \t]*(.*)$/gm)].map(
        (match) => [match[1], match[2].trim().replace(/^['"]|['"]$/g, "")],
      ),
    );
    const existingPort = Number(settings.get("PREVIEW_PORT"));
    const previewPort =
      Number.isInteger(existingPort) && existingPort > 0 && existingPort <= 65535
        ? existingPort
        : await availablePort(3001, [Number(settings.get("APP_PORT"))]);
    const additions = {
      PREVIEW_PORT: String(previewPort),
      PREVIEW_BASE_URL: `http://localhost:${previewPort}`,
      PROXY_INTERNAL_URL: `http://127.0.0.1:${previewPort}`,
      PROXY_SECRET: secret(),
      PREVIEW_MAX_SESSIONS: "100",
      PREVIEW_SESSION_TTL_MS: "3600000",
      PREVIEW_MAX_HTML_BYTES: "8388608",
      PREVIEW_ALLOWED_PRIVATE_HOSTS: "localhost,127.0.0.1",
    };
    const missing = Object.entries(additions).filter(([key]) => !settings.has(key));
    if (missing.length) {
      await appendFile(
        envPath,
        `\n# Native preview configuration added by Repère setup.\n${missing.map(([key, value]) => `${key}=${value}`).join("\n")}\n`,
      );
      console.log(
        "Added missing native preview settings; existing secrets and settings are preserved.",
      );
    } else console.log("Using existing .env; all secrets and settings are preserved.");
  }
  await chmod(envPath, 0o600);
  if (!envOnly) {
    run("docker", [...compose, "build"]);
    run("docker", [...compose, "up", "--detach", "--wait", "--wait-timeout", "180"]);
    console.log("Repère is ready. Read APP_URL and MAILPIT_URL in .env for your local addresses.");
  }
} catch (error) {
  console.error(`Setup failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
}
